/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.keendly.svetovid;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClient;

/**
 * Generated from {@link com.keendly.svetovid.DeliveryWorkflow}. 
 * Used to invoke child workflows asynchronously from parent workflow code.
 * Created through {@link DeliveryWorkflowClientFactory#getClient}.
 * <p>
 * When running outside of the scope of a workflow use {@link DeliveryWorkflowClientExternal} instead.
 */
public interface DeliveryWorkflowClient extends WorkflowClient
{

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    Promise<Void> deliver(String deliveryRequest);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    Promise<Void> deliver(String deliveryRequest, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    Promise<Void> deliver(String deliveryRequest, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    Promise<Void> deliver(Promise<String> deliveryRequest);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    Promise<Void> deliver(Promise<String> deliveryRequest, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    Promise<Void> deliver(Promise<String> deliveryRequest, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#ebookGenerated}
     */
    void ebookGenerated(String generateResult);

}