/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.keendly.svetovid;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowSelfClient;

/**
 * Generated from {@link com.keendly.svetovid.DeliveryWorkflow}. 
 * Used to continue a workflow execution as a new run.
 * Must be used from a worklfow scope. 
 */
public interface DeliveryWorkflowSelfClient extends WorkflowSelfClient
{

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    void deliver(String deliveryRequest);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    void deliver(String deliveryRequest, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    void deliver(String deliveryRequest, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    void deliver(Promise<String> deliveryRequest);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    void deliver(Promise<String> deliveryRequest, Promise<?>... waitFor);

    /**
     * Generated from {@link com.keendly.svetovid.DeliveryWorkflow#deliver}
     */
    void deliver(Promise<String> deliveryRequest, StartWorkflowOptions optionsOverride, Promise<?>... waitFor);
}