/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.keendly.svetovid;

import com.amazonaws.services.simpleworkflow.flow.DataConverter;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientBase;
import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.generic.GenericWorkflowClient;
import com.amazonaws.services.simpleworkflow.model.WorkflowExecution;
import com.amazonaws.services.simpleworkflow.model.WorkflowType;

class DeliveryWorkflowClientImpl extends WorkflowClientBase implements DeliveryWorkflowClient {

    public DeliveryWorkflowClientImpl(WorkflowExecution workflowExecution, WorkflowType workflowType,  
            StartWorkflowOptions options, DataConverter dataConverter, GenericWorkflowClient genericClient) {
        super(workflowExecution, workflowType, options, dataConverter, genericClient);
    }
    
    @Override
    public final Promise<Void> deliver(String deliveryRequest) { 
        return deliver(Promise.asPromise(deliveryRequest), (StartWorkflowOptions)null);
    }
    
    @Override
    public final Promise<Void> deliver(String deliveryRequest, Promise<?>... waitFor) {
        return deliver(Promise.asPromise(deliveryRequest), (StartWorkflowOptions)null, waitFor);
    }
    
    
    @Override
    
    public final Promise<Void> deliver(String deliveryRequest, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        return deliver(Promise.asPromise(deliveryRequest), optionsOverride, waitFor);
    }

    @Override
    public final Promise<Void> deliver(Promise<String> deliveryRequest) {
        return deliver(deliveryRequest, (StartWorkflowOptions)null);
    }

    @Override
    public final Promise<Void> deliver(Promise<String> deliveryRequest, Promise<?>... waitFor) {
        return deliver(deliveryRequest, (StartWorkflowOptions)null, waitFor);
    }

    @Override
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
    public final Promise<Void> deliver(Promise<String> deliveryRequest, StartWorkflowOptions optionsOverride, Promise<?>... waitFor) {
        Promise[] _input_ = new Promise[1];
        _input_[0] = deliveryRequest;
        return (Promise) startWorkflowExecution(_input_, optionsOverride, Void.class, waitFor);
    }
    	

    @Override
    public void ebookGenerated(String generateResult) { 
        Object[] _input_ = new Object[1];
        _input_[0] = generateResult;
        signalWorkflowExecution("ebookGenerated", _input_);
    }
}